# Translations template for nova_powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 0.0.1.dev353\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-03 10:53-0400\n"
"PO-Revision-Date: 2015-09-03 10:53-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova_powervm/virt/powervm/driver.py:131
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Esperado exatamente um host; localizados %d"

#: nova_powervm/virt/powervm/driver.py:679
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Plugue vif falhou porque a instância %s não foi localizada."

#: nova_powervm/virt/powervm/driver.py:684
msgid "Plug vif failed because of an unexpected error."
msgstr "Plugue vif falhou devido a erro inesperado."

#: nova_powervm/virt/powervm/driver.py:781
msgid "Cannot reduce disk size."
msgstr "Impossível reduzir o tamanho do disco."

#: nova_powervm/virt/powervm/exception.py:37
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"NV-5F976E2 Impossível localizar o grupo de volumes %(vol_grp)s para armazenar a "
"mídia ótica virtual dentro dele. Impossível criar o repositório de mídia. "

#: nova_powervm/virt/powervm/exception.py:44
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr ""
"NV-5E41059 Esperava localizar exatamente uma partição de gerenciamento; localizadas "
"%(count)d."

#: nova_powervm/virt/powervm/exception.py:50
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"NV-0611C68 Tendo barramento SCSI digitalizado %(bus)x na partição de gerenciamento, "
"disco com UDID %(udid)s falhou em aparecer após %(polls)d pesquisas em "
"%(timeout)d segundos."

#: nova_powervm/virt/powervm/exception.py:57
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"NV-042142B Esperava localizar exatamente um disco na partição de gerenciamento "
"em %(path_pattern)s; localizados %(count)d."

#: nova_powervm/virt/powervm/exception.py:63
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"NV-AB822D0 O dispositivo %(devpath)s ainda está presente na partição de gerenciamento "
"após tentar excluí-lo.  Pesquisado %(polls)d vezes em "
"%(timeout)d segundos."

#: nova_powervm/virt/powervm/exception.py:69
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"NV-9F22861 Falhou em mapear disco de inicialização da instância %(instance_name)s para a"
"partição de gerenciamento de qualquer Virtual I/O Server."

#: nova_powervm/virt/powervm/exception.py:75
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"NV-75BCC89 Falhou em localizar o mapeamento recém-criado do elemento de armazenamento "
"%(stg_name)s do Virtual I/O Server %(vios_name)s para a "
"partição de gerenciamento. "

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr ""
"NV-CB5875B Impossível localizar grupo de volumes '%(vg_name)s' para esta "
"operação."

#: nova_powervm/virt/powervm/exception.py:86
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr ""
"NV-DA1D957 Não é possível localizar o Cluster '%(clust_name)s' para essa "
"operação."

#: nova_powervm/virt/powervm/exception.py:91
msgid "Unable to locate any Cluster for this operation."
msgstr "NV-17B82F8 Impossível localizar um cluster para esta operação."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"NV-218A375 Localizou inesperadamente %(clust_count)d Clusters com nome correspondente "
"'%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"NV-F07AD8B Nenhum cluster_name especificado. Recusando-se a selecionar um dos "
"%(clust_count)d Clusters localizados."

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"NV-82FD24F Impossível anexar armazenamento (id: %(volume_id)s) à máquina "
"virtual %(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"NV-30C93CB Impossível desanexar volume (id: %(volume_id)s) da máquina "
"virtual %(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"NV-D26FA38 Impossível realizar etapas pré-migração em tempo real no volume (id: "
"%(volume_id)s) da máquina virtual %(instance_name)s."

#: nova_powervm/virt/powervm/live_migration.py:36
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "Migração em tempo real da instância %(name)s' falhou devido a: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:41
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"Migração em tempo real da instância '%(name)s' falhou porque o estado da migração "
"é: %(state)s"

#: nova_powervm/virt/powervm/live_migration.py:46
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"A migração em tempo real da instância '%(name)s' falhou porque ela não está pronta. "
"Motivo: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:51
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Impossível migrar instância '%(name)s' porque o tamanho da região de memória da "
"origem (%(source_mrs)d MB) não corresponde ao tamanho da região de memória do "
"destino (%(target_mrs)d MB)."

#: nova_powervm/virt/powervm/live_migration.py:58
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Impossível migrar %(name)s porque seu modo de capacidade de processador %(mode)s"
" não está na lista de modos \"%(modes)s\" suportados pelo host de destino."

#: nova_powervm/virt/powervm/live_migration.py:65
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Impossível migrar %(name)s porque o host %(host)s somente permite %(allowed)s"
" migrações simultâneas e %(running)s migrações está em execução no momento. "

#: nova_powervm/virt/powervm/live_migration.py:71
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"Impossível migrar %(name)s porque o volume %(volume)s não pode ser anexado "
"no host de destino %(host)s."

#: nova_powervm/virt/powervm/vm.py:343
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Vários conjuntos de processo compartilhados com o nome %(pool)s."

#: nova_powervm/virt/powervm/vm.py:347
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Impossível localizar o conjunto de processamento compartilhado %(pool)s"

#: nova_powervm/virt/powervm/vm.py:369
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"O atributo flavor %(attr)s deve ser True ou False. O valor atual "
"%(val)s não é permitido. "

#: nova_powervm/virt/powervm/tasks/network.py:39
msgid "Virtual interface unplug failed"
msgstr "Desconexão da interface virtual falhou"

#: nova_powervm/virt/powervm/volume/vscsi.py:175
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Falha em descobrir hdisk válido em qualquer Virtual I/O Server para o volume"
"%(volume_id)s."

