# Translations template for nova_powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 0.0.1.dev353\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-03 10:53-0400\n"
"PO-Revision-Date: 2015-09-03 10:53-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova_powervm/virt/powervm/driver.py:131
#, python-format
msgid "Expected exactly one host; found %d"
msgstr "Previsto un solo host; trovati %d"

#: nova_powervm/virt/powervm/driver.py:679
#, python-format
msgid "Plug vif failed because instance %s was not found."
msgstr "Collegamento vif non riuscito perché l'istanza %s non è stata trovata."

#: nova_powervm/virt/powervm/driver.py:684
msgid "Plug vif failed because of an unexpected error."
msgstr "Collegamento vif non riuscito a causa di un errore imprevisto."

#: nova_powervm/virt/powervm/driver.py:781
msgid "Cannot reduce disk size."
msgstr "Impossibile ridurre la dimensione del disco."

#: nova_powervm/virt/powervm/exception.py:37
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual "
"optical media within.  Unable to create the media repository."
msgstr ""
"NV-5F976E2 Impossibile individuare il gruppo di volumi %(vol_grp)s per memorizzarvi "
"i supporti ottici virtuali.  Impossibile creare il repository di supporti."

#: nova_powervm/virt/powervm/exception.py:44
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr ""
"NV-5E41059 Era previsto trovare una sola partizione di gestione; trovate "
"%(count)d."

#: nova_powervm/virt/powervm/exception.py:50
#, python-format
msgid ""
"Having scanned SCSI bus %(bus)x on the management partition, disk with "
"UDID %(udid)s failed to appear after %(polls)d polls over %(timeout)d "
"seconds."
msgstr ""
"NV-0611C68 Avendo effettuato la scansione del bus SCSI %(bus)x sulla partizione di gestione, "
"il disco con UDID %(udid)s non è comparso dopo %(polls)d poll in "
"%(timeout)d secondi."

#: nova_powervm/virt/powervm/exception.py:57
#, python-format
msgid ""
"Expected to find exactly one disk on the management partition at "
"%(path_pattern)s; found %(count)d."
msgstr ""
"NV-042142B Era previsto trovare un solo disco sulla partizione di gestione "
"su %(path_pattern)s; trovate %(count)d."

#: nova_powervm/virt/powervm/exception.py:63
#, python-format
msgid ""
"Device %(devpath)s is still present on the management partition after "
"attempting to delete it.  Polled %(polls)d times over %(timeout)d "
"seconds."
msgstr ""
"NV-AB822D0 Il dispositivo %(devpath)s è ancora presente nella partizione "
"di gestione dopo il tentativo di eliminazione.  Eseguito il poll %(polls)d volte in "
"%(timeout)d secondi."

#: nova_powervm/virt/powervm/exception.py:69
#, python-format
msgid ""
"Failed to map boot disk of instance %(instance_name)s to the management "
"partition from any Virtual I/O Server."
msgstr ""
"NV-9F22861 Impossibile associare il disco di avvio dell'istanza %(instance_name)s alla "
"partizione di gestione da qualsiasi Virtual I/O Server."

#: nova_powervm/virt/powervm/exception.py:75
#, python-format
msgid ""
"Failed to find newly-created mapping of storage element %(stg_name)s from"
" Virtual I/O Server %(vios_name)s to the management partition."
msgstr ""
"NV-75BCC89 Impossibile trovare l'associazione appena creata dell'elemento memoria "
"%(stg_name)s del Virtual I/O Server %(vios_name)s alla  "
"partizione di gestione."

#: nova_powervm/virt/powervm/exception.py:81
#, python-format
msgid "Unable to locate the volume group '%(vg_name)s' for this operation."
msgstr ""
"NV-CB5875B Impossibile individuare il gruppo di volumip '%(vg_name)s' per questa "
"operazione."

#: nova_powervm/virt/powervm/exception.py:86
#, python-format
msgid "Unable to locate the Cluster '%(clust_name)s' for this operation."
msgstr ""
"NV-DA1D957 Impossibile individuare il cluster '%(clust_name)s' per questa "
"operazione."

#: nova_powervm/virt/powervm/exception.py:91
msgid "Unable to locate any Cluster for this operation."
msgstr "NV-17B82F8 Impossibile individuare un cluster per questa operazione."

#: nova_powervm/virt/powervm/exception.py:95
#, python-format
msgid ""
"Unexpectedly found %(clust_count)d Clusters matching name "
"'%(clust_name)s'."
msgstr ""
"NV-218A375 Trovati inaspettatamente %(clust_count)d cluster che corrispondo al nome "
"'%(clust_name)s'."

#: nova_powervm/virt/powervm/exception.py:100
#, python-format
msgid ""
"No cluster_name specified.  Refusing to select one of the %(clust_count)d"
" Clusters found."
msgstr ""
"NV-F07AD8B Nessun cluster_name specificato.  Rifiutata la selezione di uno dei "
"%(clust_count)d cluster trovati."

#: nova_powervm/virt/powervm/exception.py:105
#, python-format
msgid ""
"Unable to attach storage (id: %(volume_id)s) to virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"NV-82FD24F Impossibile collegare la memoria (id: %(volume_id)s) alla "
"macchina virtuale %(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:110
#, python-format
msgid ""
"Unable to detach volume (id: %(volume_id)s) from virtual machine "
"%(instance_name)s.  %(reason)s"
msgstr ""
"NV-30C93CB Impossibile scollegare il volume (id: %(volume_id)s) dalla "
"macchina virtuale %(instance_name)s.  %(reason)s"

#: nova_powervm/virt/powervm/exception.py:115
#, python-format
msgid ""
"Unable to perform pre live migration steps on volume (id: %(volume_id)s) "
"from virtual machine %(instance_name)s."
msgstr ""
"NV-D26FA38 Impossibile eseguire i passi preliminari della migrazione live sul volume (id: "
"%(volume_id)s) dalla macchina virtuale %(instance_name)s."

#: nova_powervm/virt/powervm/live_migration.py:36
#, python-format
msgid "Live migration of instance '%(name)s' failed for reason: %(reason)s"
msgstr "La migrazione live dell'istanza '%(name)s' non è riuscita per il motivo: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:41
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because the migration state "
"is: %(state)s"
msgstr ""
"La migrazione live dell'istanza '%(name)s' non è riuscita perché lo stato della migrazione "
"è: %(state)s"

#: nova_powervm/virt/powervm/live_migration.py:46
#, python-format
msgid ""
"Live migration of instance '%(name)s' failed because it is not ready. "
"Reason: %(reason)s"
msgstr ""
"La migrazione live dell'istanza '%(name)s' non è riuscita perché non è pronta. "
"Motivo: %(reason)s"

#: nova_powervm/virt/powervm/live_migration.py:51
#, python-format
msgid ""
"Cannot migrate instance '%(name)s' because the memory region size of the "
"source (%(source_mrs)d MB) does not match the memory region size of the "
"target (%(target_mrs)d MB)."
msgstr ""
"Impossibile migrare l'istanza '%(name)s' perché la dimensione dell'area di memoria "
"dell'origine (%(source_mrs)d MB) non corrisponde alla dimensione dell'area di memoria della "
"destinazione (%(target_mrs)d MB)."

#: nova_powervm/virt/powervm/live_migration.py:58
#, python-format
msgid ""
"Cannot migrate %(name)s because its processor compatibility mode %(mode)s"
" is not in the list of modes \"%(modes)s\" supported by the target host."
msgstr ""
"Impossibile migrare %(name)s perché la sua modalità di compatibilità del processore %(mode)s"
" non è nell'elenco di modalità \"%(modes)s\" supportate dall'host di destinazione."

#: nova_powervm/virt/powervm/live_migration.py:65
#, python-format
msgid ""
"Cannot migrate %(name)s because the host %(host)s only allows %(allowed)s"
" concurrent migrations and %(running)s migrations are currently running."
msgstr ""
"Impossibile migrare %(name)s perché l'host %(host)s consente solo %(allowed)s"
" migrazioni simultanee e attualmente sono in esecuzione %(running)s migrazioni."

#: nova_powervm/virt/powervm/live_migration.py:71
#, python-format
msgid ""
"Cannot migrate %(name)s because the volume %(volume)s cannot be attached "
"on the destination host %(host)s."
msgstr ""
"Impossibile migrare %(name)s perché il volume %(volume)s non può essere collegato "
"all'host di destinazione %(host)s."

#: nova_powervm/virt/powervm/vm.py:343
#, python-format
msgid "Multiple Shared Processing Pools with name %(pool)s."
msgstr "Più pool di elaborazione condivisi con nome %(pool)s."

#: nova_powervm/virt/powervm/vm.py:347
#, python-format
msgid "Unable to find Shared Processing Pool %(pool)s"
msgstr "Impossibile trovare il pool di elaborazione condiviso %(pool)s"

#: nova_powervm/virt/powervm/vm.py:369
#, python-format
msgid ""
"Flavor attribute %(attr)s must be either True or False.  Current value "
"%(val)s is not allowed."
msgstr ""
"L'attributo versione %(attr)s deve essere True o False.  Il valore corrente "
"%(val)s non è consentito."

#: nova_powervm/virt/powervm/tasks/network.py:39
msgid "Virtual interface unplug failed"
msgstr "Scollegamento interfaccia virtuale non riuscito"

#: nova_powervm/virt/powervm/volume/vscsi.py:175
#, python-format
msgid ""
"Failed to discover valid hdisk on any Virtual I/O Server for volume "
"%(volume_id)s."
msgstr ""
"Impossibile rilevare un disco valido su qualsiasi Virtual I/O Server per il volume "
"%(volume_id)s."

